# access_key_id: ENV.fetch('BENTO_ACCESS_KEY_ID'),
# secret_access_key: ENV.fetch('BENTO_SECRET_ACCESS_KEY'),


# # Tokyoリージョン
# # bucket: ENV.fetch('S3_BUCKET_NAME'),
# # s3_region: ENV.fetch('AWS_REGION'),
# # s3_host_name: 's3-ap-northeast-1.amazonaws.com'

# # US-stamdardリージョン
# bucket: 'bento-bento',
# s3_host_name: 's3.amazonaws.com '
# s3_region: 'us-east-1'